Add getter for material params
WonderlandEngine/api pull request #18
Opened 2023-12-20 11:05 UTC by SignorPipo

2023-12-21 08:52 UTC, Squareys requested changes
Did a quick first review! Generally seems like a useful change to avoid the garbage around color properties.

CC @DavidPeicho What do you think?

2023-12-21 08:52 UTC, Squareys commented on src/wonderland.ts
> +import { MaterialDefinition, WASM } from './wasm.js';
Make sure to apply our prettier config.

2023-12-21 08:52 UTC, Squareys commented on src/wonderland.ts
> +    getParam(name: string, out: any = null): any {
`any` can be restricted to the actual types that can be returned. I.e. string is not an option, but number, ArrayLike...
`out` can also only be null or ArrayLike

2023-12-21 11:25 UTC, DavidPeicho commented
> Did a quick first review! Generally seems like a useful change to avoid the garbage around color properties.
> 
> CC @DavidPeicho What do you think?

Not only for garbage collection @Squareys, but doing `material.property = ...` is dangerous, since we can't really throw if the property doesn't exist (because a user might monkey patch an object), and the user could fail. We recently just got this error in a project, where the user used `material.texture = ` instead of `material.flatTexture = `.

So in general we should force people to use `(get/set)Param` yes. I haven't reviewed the MR properly yet

2023-12-27 11:35 UTC, DavidPeicho commented on src/wonderland.ts
> +        out: number | NumberArray | Texture
`number` isn't possible here, since there is no reference types in JS., `Texture` is useless as well

2023-12-27 11:38 UTC, DavidPeicho commented on src/wonderland.ts
> +    setParam(name: string, value: number | NumberArray | Texture) {
I don't think this should return a boolean, it should just throw if it failed

2023-12-27 11:40 UTC, DavidPeicho commented on src/wonderland.ts
> +     * Get the definition of the material parameter, which includes it's type and the amount of values.
> and component count.

2023-12-27 11:40 UTC, DavidPeicho commented on src/wonderland.ts
> +     * @param name name of the material parameter.
> Name of the material parameter.

Missing caps

2023-12-27 11:40 UTC, DavidPeicho commented on src/wonderland.ts
> +     * If the param exists on the material or not.
> Check whether the parameter exists on the material or not.

2023-12-27 11:41 UTC, DavidPeicho commented on src/wonderland.ts
> +     * @param name name of the material parameter.
Missing caps

2023-12-27 11:41 UTC, DavidPeicho commented on src/wonderland.ts
> +     * @returns true if the parameter exists on the material, false otherwise.
> `true` if the parameter exists on the material, `false` otherwise.

You are missing the backticks

2023-12-27 11:42 UTC, DavidPeicho commented on src/wonderland.ts
> +        const materialParamDefinition = this.getParamDefinition(name);
This boils down to:

```ts
return !!this.getParamDefinition(name);
```

2023-12-27 11:42 UTC, DavidPeicho commented on src/wonderland.ts
> +        const materialParamDefinition = this.getParamDefinition(name);
Probably better to use `has` on `materialParamDefinition` tho

2023-12-27 11:42 UTC, DavidPeicho commented on src/wonderland.ts
> +     * @param name name of the material parameter.
Missing caps

2023-12-27 11:42 UTC, DavidPeicho commented on src/wonderland.ts
> +     * @param out destination of the material parameter value, its type and size depend on the parameter definition.
Missing caps

2023-12-27 11:43 UTC, DavidPeicho commented on src/wonderland.ts
> +     * @throws When the parameter is not yet supported.
Just put the throws on one keyword:

> When the parameter is not yet supported, or if the parameter type is not valid.

2023-12-27 11:44 UTC, DavidPeicho commented on src/wonderland.ts
> +            throw new Error(`Reading parameter '${name}' not yet supported`);
The error message is wrong here I believe, shouldn't it be:

> Parameter '${name}' does not exist on this material

2023-12-27 11:44 UTC, DavidPeicho commented on src/wonderland.ts
> +    _setMaterialParamValue(
Should be `private`

2023-12-27 13:10 UTC, SignorPipo commented on src/wonderland.ts
> +    getParam(name: string, out: any = null): any {
@DavidPeicho here J says this should return number for example, related to your comment

2023-12-27 13:17 UTC, SignorPipo commented on src/wonderland.ts
> +        out: number | NumberArray | Texture
I'm not sure about this, getParam can return a number for sure, you can see that in the switch case

2024-01-04 11:05 UTC, DavidPeicho commented
So, one thing that would be nice is not to have a generic `set/getParam` for every param, but rather have:

```ts
getColor(name: string, out: Float32Array): Float32Array;
setColor(name: string, v: Float32Array): Float32Array;
getInt(name: string): number;
setInt(name: string, v: number): number;
```

This will allow to:
* Get better methods and parameters check, since only colors can use a `out` parameter
* Get better typings

Now the question is whether we keep a generic `get/setType`, or go further and do:

```ts
getDiffuseColor(out: Float32Array);
```

So something similar to what we have right now, except we create getters/setters instead of using a proxy.

### Benchmarks

Here is a benchmark comparing the speed of both method: https://gist.github.com/DavidPeicho/10dc2295fec20624c951f60951be8b6a

On Chrome, the string version is 37% slower on a M2. On Safari, it's 27% faster. We can probably amortize the prototype lookup on safari by storing classes upon definition setup.

2024-01-04 15:47 UTC, closed without merging